// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package icu.aierx.services;

public interface RegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:icu.aierx.services.RegisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 错误码
   * </pre>
   *
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>string err_msg = 2;</code>
   * @return The errMsg.
   */
  java.lang.String getErrMsg();
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>string err_msg = 2;</code>
   * @return The bytes for errMsg.
   */
  com.google.protobuf.ByteString
      getErrMsgBytes();
}
