// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package icu.aierx.services;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:icu.aierx.services.RegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 姓名
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * 姓名
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 手机号
   * </pre>
   *
   * <code>string tel = 2;</code>
   * @return The tel.
   */
  java.lang.String getTel();
  /**
   * <pre>
   * 手机号
   * </pre>
   *
   * <code>string tel = 2;</code>
   * @return The bytes for tel.
   */
  com.google.protobuf.ByteString
      getTelBytes();

  /**
   * <pre>
   * 邮箱：可选
   * </pre>
   *
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <pre>
   * 邮箱：可选
   * </pre>
   *
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
